
## DAX Measure Table

_Measure and Model Info = 

// This measure table is designed to do two things: 1. Document all columns and measures in the data model 2. Serve as the central measure table.

VAR mea = INFO.VIEW.MEASURES()
VAR col = INFO.VIEW.COLUMNS()

RETURN 
// The segment column allows for a simple way to slice between measures and columns.

UNION(
ADDCOLUMNS( 
    SUMMARIZE( mea, [Name], [DisplayFolder], [Table], [DataType], [DataCategory], [Description],[Expression]), "Segment", "Measures"),

// TMDL + a simple prompt to write descriptions is a great task for Copilot (or other AI methods) 

ADDCOLUMNS( 
    SUMMARIZE( col, [Name], [DisplayFolder], [Table], [DataType], [DataCategory], [Description],[Expression]), "Segment", "Columns"))
